<?php

namespace Brasa\GeneralBundle\Repository;

/**
 * GenFavoritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenFavoritoRepository extends \Doctrine\ORM\EntityRepository {

    public function eliminar($arrSeleccionados) {
         $em = $this->getEntityManager();
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigoFavorito) {
                $arFavorito = $em->getRepository('BrasaGeneralBundle:GenFavorito')->find($codigoFavorito);
                $em->remove($arFavorito);
            }
        }
        $em->flush();
    }

}
