<?php

namespace Brasa\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenAsesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenLogRepository extends EntityRepository {

    public function listaDql($codigoUsuario, $codigoDocumento, $id) {
        $dql = "SELECT l FROM BrasaGeneralBundle:GenLog l WHERE l.codigoDocumentoFk = " . $codigoDocumento . " AND l.id = " . $id;
        return $dql;
    }

    public function crearLog($codigoUsuario, $codigoDocumento, $codigoAccion, $id) {
        $em = $this->getEntityManager();
        $arUsuario = $em->getRepository('BrasaSeguridadBundle:User')->find($codigoUsuario);
        $arDocumento = $em->getRepository('BrasaSeguridadBundle:SegDocumento')->find($codigoDocumento);
        $arAccion = $em->getRepository('BrasaGeneralBundle:GenLogAccion')->find($codigoAccion);
        $arLog = new \Brasa\GeneralBundle\Entity\GenLog();
        $arLog->setDocumentoRel($arDocumento);
        $arLog->setUsuarioRel($arUsuario);
        $arLog->setLogAccionRel($arAccion);
        $arLog->setFecha(new \DateTime('now'));
        $arLog->setId($id);
        $em->persist($arLog);
        $em->flush();
        return TRUE;
    }

}
