<?php

namespace Brasa\GeneralBundle\Repository;

/**
 * GenNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
