<?php

namespace Brasa\GeneralBundle\Repository;

/**
 * GenRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
