<?php

namespace Brasa\InventarioBundle\Repository;

/**
 * InvOrdenCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvOrdenCompraRepository extends \Doctrine\ORM\EntityRepository
{
}
