<?php

namespace Brasa\InventarioBundle\Repository;

/**
 * InvOdenCompraDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvOrdenCompraDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
