<?php

namespace Brasa\InventarioBundle\Repository;

/**
 * invOrdenCompraDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invOrdenCompraDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
