<?php

namespace Brasa\InventarioBundle\Repository;

/**
 * InvSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvSolicitudDocumentoRepository extends \Doctrine\ORM\EntityRepository {

}
