<?php

namespace Brasa\InventarioBundle\Repository;

/**
 * InvSolicitudDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvSolicitudDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
