parameters:
#    brasa_contabilidad.example.class: Brasa\ContabilidadBundle\Example

services:
#    brasa_contabilidad.example:
#        class: %brasa_contabilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
