<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * ProgramacionSimuladorDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramacionSimuladorDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
