<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurCompensacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurCompensacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
