<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurConfiguracionCuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
