<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurClienteContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurClienteContactoRepository extends \Doctrine\ORM\EntityRepository {

    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados AS $codigo) {
                $ar = $em->getRepository('BrasaTurnoBundle:TurClienteContacto')->find($codigo);
                $em->remove($ar);
            }
            $em->flush();
        }
    }

}
