<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurControlPuestoDetalleTipoNovedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurControlPuestoDetalleTipoNovedadRepository extends \Doctrine\ORM\EntityRepository
{
}
