<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurProgramacionSimuladorDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurProgramacionSimuladorDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
