<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurProgramacionSimuladorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurProgramacionSimuladorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDqlConsultaDetalles() {
        $em = $this->getEntityManager();
        $consulta = "SELECT s FROM BrasaTurnoBundle:TurProgramacionSimulador s JOIN s.recursoRel";
        return $consulta;
    }
}
