<?php

namespace Brasa\TurnoBundle\Repository;

/**
 * TurServicioTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurServicioTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
