parameters:
#    brasa_logistica.example.class: Brasa\TransporteBundle\Example

services:
#    brasa_logistica.example:
#        class: %brasa_logistica.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
