imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BrasaSeguridadBundle/Resources/config/services.yml" }
    - { resource: "@BrasaGeneralBundle/Resources/config/services.yml" }
    - { resource: "@BrasaTransporteBundle/Resources/config/services.yml" }
    - { resource: "@BrasaRecursoHumanoBundle/Resources/config/services.yml" }
    - { resource: "@BrasaContabilidadBundle/Resources/config/services.yml" }
    - { resource: "@BrasaTurnoBundle/Resources/config/services.yml" }
    - { resource: "@BrasaCarteraBundle/Resources/config/services.yml" }
    - { resource: "@BrasaAdministracionDocumentalBundle/Resources/config/services.yml" }
    - { resource: "@BrasaInventarioBundle/Resources/config/services.yml" }
    - { resource: "@BrasaTesoreriaBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']
        # resources: ['bootstrap_3_horizontal_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
        
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template        

services:
    mensajes_brasa:
        class:        Brasa\GeneralBundle\MisClases\Mensajes   
    funciones_brasa:
        class:        Brasa\GeneralBundle\MisClases\Funciones

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ... 
        
sonata_admin:
    title:                'SogaApp Admin'
    title_logo:           imagenes/logos/logo.jpg
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
       
    dashboard:
        groups:                    
            app.admin.group.recursohumano:
                label: Recurso humano
                label_catalogue: Brasa\RecursoHumanoBundle
                items:
                    - admin.recursohumano.incapacidadtipo
                    - admin.recursohumano.requisitotipo
                    - admin.recursohumano.facturaconcepto
                    - admin.recursohumano.estudiotipo
                    - admin.recursohumano.seleccionrequisicionexperiencia
                    
            app.admin.group.turno:
                label: Programacion turno
                label_catalogue: Brasa\TurnoBundle
                items:
                    - admin.turno.centrooperacion
                    
            app.admin.group.inventario:
                label: Inventario
                label_catalogue: Brasa\InventarioBundle
                items:
                    - admin.inventario.marca 
                    - admin.inventario.item
                    - admin.inventario.area
                    
            app.admin.group.general:
                label: General
                label_catalogue: Brasa\GeneralBundle
                items:
                    - admin.general.sectorcomercial
                    - admin.general.sectoreconomico
                    - admin.general.cobertura
                    - admin.general.dimension
                    - admin.general.origencapital
                    - admin.general.origenjudicial
                    - admin.general.pais
                    - admin.general.departamento
                    - admin.general.ciudad
                    
            