# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    # ...
    admin.inventario.marca:
        class: Brasa\InventarioBundle\Admin\InventarioMarcaAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvMarca, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Marca }
            
    admin.inventario.item:
        class: Brasa\InventarioBundle\Admin\InventarioItemAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Item }     
            
    admin.inventario.area:
        class: Brasa\InventarioBundle\Admin\InventarioAreaAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvArea, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Area }      
            
    admin.recursohumano.incapacidadtipo:
        class: Brasa\RecursoHumanoBundle\Admin\IncapacidadTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuIncapacidadTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Incapacidad tipo }            
            
    admin.recursohumano.facturaconcepto:
        class: Brasa\RecursoHumanoBundle\Admin\FacturaConceptoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuFacturaConcepto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Factura concepto }             