# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    # ................... administracion del modulo de inventario......................................................................
    admin.inventario.marca:
        class: Brasa\InventarioBundle\Admin\InventarioMarcaAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvMarca, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Marca }
            
    admin.inventario.item:
        class: Brasa\InventarioBundle\Admin\InventarioItemAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Item }     
            
    admin.inventario.area:
        class: Brasa\InventarioBundle\Admin\InventarioAreaAdmin
        arguments: [~, Brasa\InventarioBundle\Entity\InvArea, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Area }      
    
    # ................... administracion del modulo de recurso humano..................................................................
    
    admin.recursohumano.incapacidadtipo:
        class: Brasa\RecursoHumanoBundle\Admin\IncapacidadTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuIncapacidadTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Incapacidad tipo }            
            
    admin.recursohumano.facturaconcepto:
        class: Brasa\RecursoHumanoBundle\Admin\FacturaConceptoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuFacturaConcepto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Factura concepto }
            
    admin.recursohumano.facturatipo:
        class: Brasa\RecursoHumanoBundle\Admin\FacturaTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuFacturaTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Factura tipo }
            
    admin.recursohumano.facturaservicio:
        class: Brasa\RecursoHumanoBundle\Admin\FacturaServicioAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuFacturaServicio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Factura servicio }
              
    admin.recursohumano.estudiotipo:
        class: Brasa\RecursoHumanoBundle\Admin\EmpleadoEstudioTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuEmpleadoEstudioTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Estudio tipo }
            
    admin.recursohumano.seleccionrequisicionexperiencia:
        class: Brasa\RecursoHumanoBundle\Admin\SeleccionRequisicionExperienciaAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuSeleccionRequisicionExperiencia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Seleccion requisicion experiencia }
            
    admin.recursohumano.seleccionrequisicionmotivo:
        class: Brasa\RecursoHumanoBundle\Admin\SeleccionRequisitoMotivoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuSeleccionRequisitoMotivo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Seleccion requisicion motivo }
            
    admin.recursohumano.requisitotipo:
        class: Brasa\RecursoHumanoBundle\Admin\RequisitoTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuRequisitoTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Requisito tipo }
            
    admin.recursohumano.poligrafiatipo:
        class: Brasa\RecursoHumanoBundle\Admin\PoligrafiaTipoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuPoligrafiaTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Poligrafia tipo }

    admin.recursohumano.reclamoconcepto:
        class: Brasa\RecursoHumanoBundle\Admin\ReclamoConceptoAdmin
        arguments: [~, Brasa\RecursoHumanoBundle\Entity\RhuReclamoConcepto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Reclamo concepto }          
            
    # .................. administracion modulo programacion de turnos .................................................................
    
    admin.turno.centrooperacion:
        class: Brasa\TurnoBundle\Admin\CentroOperacionAdmin
        arguments: [~, Brasa\TurnoBundle\Entity\TurCentroOperacion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Centro de operacion }
    
    admin.turno.modalidadservicio:
        class: Brasa\TurnoBundle\Admin\ModalidadServicioAdmin
        arguments: [~, Brasa\TurnoBundle\Entity\TurModalidadServicio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Modalidad servicio }
    
    admin.turno.serviciotipo:
        class: Brasa\TurnoBundle\Admin\ServicioTipoAdmin
        arguments: [~, Brasa\TurnoBundle\Entity\TurServicioTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Servicio tipo }
            
    admin.turno.controlpuestodetalletiponovedad:
        class: Brasa\TurnoBundle\Admin\ControlPuestoDetalleTipoNovedadAdmin
        arguments: [~, Brasa\TurnoBundle\Entity\TurControlPuestoDetalleTipoNovedad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Control puesto tipo novedad }
            
    admin.turno.compensaciontipo:
        class: Brasa\TurnoBundle\Admin\CompensacionTipoAdmin
        arguments: [~, Brasa\TurnoBundle\Entity\TurCompensacionTipo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Compensacion tipo }
            
    # .................. administracion modulo contabilidad .................................................................
    
    admin.contabilidad.sucursales:
        class: Brasa\ContabilidadBundle\Admin\SucursalAdmin
        arguments: [~, Brasa\ContabilidadBundle\Entity\CtbSucursal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sucursal }
            
    # .................. administracion del modulo general .............................................................................
            
    admin.general.sectorcomercial:
        class: Brasa\GeneralBundle\Admin\SectorComercialAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenSectorComercial, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sector comercial }
            
    admin.general.sectoreconomico:
        class: Brasa\GeneralBundle\Admin\OrigenJudicialAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenSectorEconomico, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sector economico }
            
    admin.general.cobertura:
        class: Brasa\GeneralBundle\Admin\CoberturaAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenCobertura, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cobertura }
    
    admin.general.dimension:
        class: Brasa\GeneralBundle\Admin\DimensionAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenDimension, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Dimension }
       
    admin.general.origencapital:
        class: Brasa\GeneralBundle\Admin\OrigenCapitalAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenOrigenCapital, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Origen capital }
            
    admin.general.origenjudicial:
        class: Brasa\GeneralBundle\Admin\OrigenJudicialAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenOrigenJudicial, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Origen judicial }
            
    admin.general.pais:
        class: Brasa\GeneralBundle\Admin\PaisAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenPais, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pais }
            
    admin.general.departamento:
        class: Brasa\GeneralBundle\Admin\DepartamentoAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenDepartamento, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Departamento }
            
    admin.general.ciudad:
        class: Brasa\GeneralBundle\Admin\CiudadAdmin
        arguments: [~, Brasa\GeneralBundle\Entity\GenCiudad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ciudad }
            
    # .................. administracion del modulo general .............................................................................
            
    admin.seguridad.grupo:
        class: Brasa\SeguridadBundle\Admin\GrupoAdmin
        arguments: [~, Brasa\SeguridadBundle\Entity\SegGrupo, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Grupo }