<?php

namespace Brasa\ContabilidadBundle\Repository;

/**
 * CtbInconsistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtbInconsistenciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaDQL() {        
        $dql   = "SELECT i FROM BrasaContabilidadBundle:CtbInconsistencia i WHERE r.codigoInconsistenciaPk <> 0";
        
        return $dql;
    }           

}
