<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuCierreMesRepository extends EntityRepository {
    public function listaDql() {        
        $em = $this->getEntityManager();
        $dql   = "SELECT cm FROM BrasaRecursoHumanoBundle:RhuCierreMes cm WHERE cm.codigoCierreMesPk <> 0";
        $dql .= " ORDER BY cm.anio, cm.mes ASC";
        return $dql;
    }                            
    
}