<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuContratoAdicionTipoRepository extends EntityRepository { 
    
    public function listaDql() {        
        $dql   = "SELECT cat FROM BrasaRecursoHumanoBundle:RhuContratoAdicionTipo cat WHERE cat.codigoContratoAdicionTipoPk <> 0";        
        $dql .= " ORDER BY cat.codigoContratoAdicionTipoPk";
        return $dql;
    }     
}