<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuCapacitacionDetalleRepository extends EntityRepository {
    
    public function listaDql($strCargo = "", $strCentroCosto = "", $strIdentificacion = "", $strNombre = "", $strCodigoCliente = "", $strNombreCliente = "", $strPuesto) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT e,p,c FROM BrasaRecursoHumanoBundle:RhuEmpleado e LEFT JOIN e.puestoRel p LEFT JOIN p.clienteRel c WHERE e.codigoEmpleadoPk <> 0";
  
        if($strCargo != "") {
            $dql .= " AND e.codigoCargoFk = " . $strCargo;
        }
        if($strCentroCosto != "") {
            $dql .= " AND e.codigoCentroCostoFk = " . $strCentroCosto;
        }
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if($strNombre != "" ) {
            $dql .= " AND e.nombreCorto LIKE '%" . $strNombre . "%'";
        }
        if($strCodigoCliente != "" ) {
            $dql .= " AND c.codigoClienteFk = '" . $strCodigoCliente . "'";
        }
        if($strNombreCliente != "" ) {
            $dql .= " AND c.nombreCorto LIKE '%" . $strNombreCliente . "%'";
        }
        if($strPuesto != "") {
            $dql .= " AND e.codigoPuestoFk = " . $strPuesto;
        }
        //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
        return $dql;
    }     
    
    public function listaDetalleDql($strTipo = "", $strTema = "", $boolEstado = "", $strDesde = "", $strHasta = "", $strCodigoZona = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT cd, c FROM BrasaRecursoHumanoBundle:RhuCapacitacionDetalle cd JOIN cd.capacitacionRel c WHERE c.codigoCapacitacionPk <> 0";        
        if($strTipo != "") {
            $dql .= " AND c.codigoCapacitacionTipoFk = " . $strTipo;
        }
        if($strTema != "" ) {
            $dql .= " AND c.tema LIKE '%" . $strTema . "%'";
        }
        if($strCodigoZona != "") {
            $dql .= " AND c.codigoZonaFk = " . $strCodigoZona;
        }
        if($boolEstado == 1 ) {
            $dql .= " AND c.estado = 1";
        }
        if($boolEstado == "0") {
            $dql .= " AND c.estado = 0";
        }
        if($strDesde != "" || $strDesde != 0){
            $dql .= " AND c.fechaCapacitacion >='" . $strDesde . "'";
        }
        if($strHasta != "" || $strHasta != 0) {
            $dql .= " AND c.fechaCapacitacion <='" .  $strHasta. "'";
        }
        $dql .= " ORDER BY c.fechaCapacitacion DESC";
        return $dql;
    }    
    
    
}