<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuCentroTrabajoRepository extends EntityRepository {
    
    public function listaDql ($strNombre = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT t, c FROM BrasaRecursoHumanoBundle:RhuCentrotrabajo t JOIN t.clienteRel c WHERE t.codigoClienteFk <> 0";
        if($strNombre != "") {
            $dql .= " AND t.nombre LIKE '%". $strNombre."%'";
          
        }   
       $dql .= " ORDER BY t.codigoCentroTrabajoPk ASC";
        return $dql;
    }
}
