<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmpleadoFamiliaRepository extends EntityRepository {
    
    public function listaDqlGrupoFamiliar($strNombre = "", $strIdentificacion = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT p, e FROM BrasaRecursoHumanoBundle:RhuEmpleadoFamilia p JOIN p.empleadoRel e WHERE p.codigoEmpleadoFk <> 0";
        if($strNombre != "") {
            $dql .= " AND e.nombreCorto = " . $strNombre;
        }   
        if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
       
        return $dql;
    }
}