<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuEmbargoRepository extends EntityRepository {
    
    public function listaDql($numero = "", $numeroIdentificacion = "", $strFechaDesde = "", $strFechaHasta = "" ) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT e FROM BrasaRecursoHumanoBundle:RhuEmbargo e JOIN e.empleadoRel em WHERE e.codigoEmbargoPk <> 0";
        if($numeroIdentificacion != "" ) {
            $dql .= " AND em.numeroIdentificacion LIKE '%" . $numeroIdentificacion . "%'";
        }
        if($numero != "" ) {
            $dql .= " AND e.numero = " . $numero;
        }
        if($strFechaDesde != "" || $strFechaDesde != 0){
            $dql .= " AND e.fecha >='" . $strFechaDesde . "'";
        }
        if($strFechaHasta != "" || $strFechaHasta != 0) {
            $dql .= " AND e.fecha <='" . $strFechaHasta . "'";
        }
        $dql .= " ORDER BY e.codigoEmbargoPk DESC";
        return $dql;
    }                    
        
}