<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuFacturaDetalleRepository extends EntityRepository {
    
    public function devuelveNumeroFacturasDetalle($codigoFactura) {
        $em = $this->getEntityManager();
        $dql   = "SELECT COUNT(f.codigoFacturaDetallePk) FROM BrasaRecursoHumanoBundle:RhuFacturaDetalle f WHERE f.codigoFacturaFk = " . $codigoFactura;
        $query = $em->createQuery($dql);
        $douNumeroFacturasDetalle = $query->getSingleScalarResult();
        return $douNumeroFacturasDetalle;
    } 
    
    public function listaCliente($codigoCliente, $codigoFactura = "", $tipo = "") {
        $dql   = "SELECT fd FROM BrasaRecursoHumanoBundle:RhuFacturaDetalle fd JOIN fd.facturaRel f JOIN f.facturaTipoRel ft WHERE f.codigoClienteFk =  " . $codigoCliente . " ";
        
        if($codigoFactura != '') {
            $dql .= "AND fd.codigoFacturaFk = " . $codigoFactura . " ";  
        }    
        if($tipo != '') {
            $dql .= "AND ft.tipo = " . $tipo . " ";  
        }        
        $dql .= " ORDER BY fd.codigoFacturaDetallePk DESC";
        return $dql;
    }     
    
}