<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPagoBancoDetalleRepository extends EntityRepository {        
    
    public function listaDetalleDql($codigoPagoBanco) {                
        $dql   = "SELECT pbd FROM BrasaRecursoHumanoBundle:RhuPagoBancoDetalle pbd WHERE pbd.codigoPagoBancoFk = " . $codigoPagoBanco . " ";           
        $dql .= " ORDER BY pbd.codigoBancoFk DESC";
        return $dql;
    }     
    public function listaDQL($strFecha = "") {                
        $dql   = "SELECT pbd FROM BrasaRecursoHumanoBundle:RhuPagoBancoDetalle pbd WHERE pbd.codigoPagoBancoPk <> 0";
        if($strFecha != "") {
            $dql .= " AND pb.fechaAplicacion = '" .$strFecha. "'";
        }    
        
        $dql .= " ORDER BY pb.codigoPagoBancoPk";
        return $dql;
    }     
    
    public function pendientesContabilizarDql() {        
        $dql   = "SELECT pbd FROM BrasaRecursoHumanoBundle:RhuPagoBancoDetalle pbd WHERE pbd.estadoContabilizado = 0";       
        $dql .= " ORDER BY pbd.codigoPagoBancoDetallePk DESC";
        return $dql;
    }  
    
    public function listaPagoBancoDetalleDql( $strIdentificacion = "", $strDesde = "", $strHasta = "") {        
        $em = $this->getEntityManager();
        $dql   = "SELECT pd, p, e FROM BrasaRecursoHumanoBundle:RhuPagoBancoDetalle pd JOIN pd.pagoBancoRel p JOIN pd.empleadoRel e WHERE pd.codigoPagoBancoDetallePk <> 0";
          if($strIdentificacion != "" ) {
            $dql .= " AND e.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'"; 
        }
        if($strDesde != "") {
            $dql .= " AND p.fechaAplicacion >= '" . $strDesde . "'";
        }
        if($strHasta != "") {
            $dql .= " AND p.fechaAplicacion <= '" . $strHasta . "'";
        } 
        $dql .= " ORDER BY p.codigoPagoBancoPk DESC";
        return $dql;
    }      

}