<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuProyeccionRepository extends EntityRepository {   
    
    public function listaDql($strIdentificacion = "", $strHasta = "") {        
            $em = $this->getEntityManager();
            $dql   = "SELECT p FROM BrasaRecursoHumanoBundle:RhuProyeccion p JOIN p.contratoRel c JOIN p.empleadoRel e WHERE p.codigoProyeccionPk <> 0";
            if($strIdentificacion != "") {
                $dql .= " AND e.numeroIdentificacion = " . $strIdentificacion;
            }
            if($strHasta != "") {
                $dql .= " AND p.fechaHasta <='" . $strHasta . "'";
            }
            //$dql .= " ORDER BY p.empleadoRel.nombreCorto";
            return $dql;
        }
        
        
}