<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuPagoAdicionalPeriodoRepository extends EntityRepository {
    
    public function listaDql($estadoCerrado = "") {
        $em = $this->getEntityManager();
        $dql   = "SELECT pap FROM BrasaRecursoHumanoBundle:RhuPagoAdicionalPeriodo pap WHERE pap.codigoPagoAdicionalPeriodoPk <> 0 ";
        if($estadoCerrado == 1 ) {
            $dql .= " AND pap.estadoCerrado = 1";
        }
        if($estadoCerrado == '0' ) {
            $dql .= " AND pap.estadoCerrado = 0";
        } 
        $dql .= " ORDER BY pap.codigoPagoAdicionalPeriodoPk DESC";
        return $dql;
    } 

}