<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuRequisitoCargoRepository extends EntityRepository {       
    public function listaDql($strCodigoCargo = "") {                
        $dql   = "SELECT rc FROM BrasaRecursoHumanoBundle:RhuRequisitoCargo rc WHERE rc.codigoRequisitoCargoPk <> 0 ";        
        if($strCodigoCargo != "") {
             $dql .= " AND rc.codigoCargoFk = " . $strCodigoCargo;
        }
        $dql .= " ORDER BY rc.codigoCargoFk";
        return $dql;
    }      
}