<?php

namespace Brasa\RecursoHumanoBundle\Repository;

/**
 * RhuSeleccionRequisitoMotivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuSeleccionRequisitoMotivoRepository extends \Doctrine\ORM\EntityRepository
{
}
