<?php

namespace Brasa\RecursoHumanoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuVisitaRepository extends EntityRepository {

    public function listaDQL($strIdentificacion = "", $codigoVisitaTipo = "", $validarVencimiento = "") {
        $dql = 
              "SELECT v "
            . "FROM BrasaRecursoHumanoBundle:RhuVisita v "
            . "WHERE v.codigoVisitaPk <> 0";
        if ($strIdentificacion != "") {
            $dql .= " AND p.numeroIdentificacion LIKE '%" . $strIdentificacion . "%'";
        }
        if ($codigoVisitaTipo != "") {
            $dql .= " AND v.codigoVisitaTipoFk = " . $codigoVisitaTipo;
        }
        if ($validarVencimiento == 1) {
            $dql .= " AND v.validarVencimiento = 1";
        }
        if ($validarVencimiento == "0") {
            $dql .= " AND v.validarVencimiento = 0";
        }
        $dql .= " ORDER BY v.codigoVisitaPk DESC";
        return $dql;
    }

    //lista visitas con las fecha de vencimiento
    public function listaVisitasFechaVencimientoDQL($strIdentificacion = "", $strCodigoCentroCosto = "", $strCodigoVisitaTipo = "", $strVencimiento = "") {
        $dql = "SELECT v, e FROM BrasaRecursoHumanoBundle:RhuVisita v JOIN v.empleadoRel e WHERE v.codigoVisitaPk <> 0 AND v.validarVencimiento = 1";
        if ($strCodigoVisitaTipo != "") {
            $dql .= " AND v.codigoVisitaTipoFk = " . $strCodigoVisitaTipo;
        }

        if ($strCodigoCentroCosto != "") {
            $dql .= " AND e.codigoCentroCostoFk = " . $strCodigoCentroCosto;
        }
        if ($strIdentificacion != "") {
            $dql .= " AND e.numeroIdentificacion = '" . $strIdentificacion . "'";
        }
        if ($strVencimiento != "") {
            $dql .= " AND v.fechaVence <='" . $strVencimiento . "'";
        }
        return $dql;
    }

    public function detalleCobro($codigoCobro) {
        $em = $this->getEntityManager();
        $dql = "SELECT e FROM BrasaRecursoHumanoBundle:RhuVisita e WHERE e.codigoCobroFk = " . $codigoCobro;
        return $dql;
    }
    
    public function pendienteCobrarCobro($codigoCliente) {        
        $em = $this->getEntityManager();
        $dql   = "SELECT v FROM BrasaRecursoHumanoBundle:RhuVisita v WHERE v.estadoCobrado = 0 "
                . " AND v.codigoClienteFk = " . $codigoCliente. "";
        return $dql;
    }

}
