parameters:
#    brasa_cartera.example.class: Brasa\CarteraBundle\Example

services:
#    brasa_cartera.example:
#        class: %brasa_cartera.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
