parameters:
#    brasa_inventario.example.class: Brasa\InventarioBundle\Example

services:
#    brasa_inventario.example:
#        class: %brasa_inventario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
