parameters:
#    brasa_general.example.class: Brasa\GeneralBundle\Example

services:
#    brasa_general.example:
#        class: %brasa_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
